export class WaitingContainer {


    amount: number;
    extraAmount: number ;
    vehicleNumber: string ;
    destination: string;
    operatorName: string;
    checkInDate : string;
    checkInTime : string;
    checkOutDate : string;
    checkOutTime :string ;
    nextBillingDate : string;
    searchFromDate : string;
    searchToDate : string;
    searchFromOutDate : string;
    searchToOutDate :string ;
    environmentType : string;
    transporterName : string;
    branchId :number;
    isEmptyContainer : boolean ;
    isCustomOfficer :boolean ;
    checkOutOperator : string ;
    customOfficer : string ;
    customOutDateTime :string ;
    customDateTime : string;
    customOutDate : string;
    isEdited :number ;
    isForParking :boolean ;
    receiptError : string;
    searchText : string;
    searchby : string;
    id : number;
    entryType : number;
    roadType : number ;
    stateAbbrivation : string ;
    districtCode :number ;
    series : string;
    seriesNumber :string;
    containerSeries : string;
    containerNumber : string;
    containerSeries2 :string ;
    containerNumber2 :string;
    isDeleted : boolean;
    addedBy :string;
    addedOn : string;
    inDateTime :string;
    updatedBy :string ;
    updatedOn : string;
    receiptNo :string ;
    addedDate : string;
    checkOutDateTime : string;
    outDateTime : string;
    outDate : string;
    transporter : string;
    transporterId :string;
    sealNumber1 : string;
    sealNumber2 : string;
    sealNumber3 : string;
    sealNumber4 : string;
    chaNumber : string;
    shippingBillNumber :string ;
    shippingBillDate : string;
    vessel : string;
    pinNumber : number;
    paymentMode : number;
    containerType :number ;
    driverName : string;
    driverContactNumber :number;
    cutOffDate1 : string;
    cutOffDate2 : string;
    isCutOffValid :boolean ;
    isGTIContainerApproved : boolean ;
    allowEditingEntry :boolean ;

   
     
    constructor(){
        
       this.amount = null;
       this.extraAmount =null ;
       this.vehicleNumber = null;
       this.destination = null;
       this.operatorName = null;
       this.checkInDate  = null;
       this.checkInTime  =null;
       this.checkOutDate  = null;
       this.checkOutTime  = null;
       this.nextBillingDate  = null;
       this.searchFromDate  = null;
       this.searchToDate  = null;
       this.searchFromOutDate  =null ;
       this.searchToOutDate  = null;
       this.environmentType  = null;
       this.transporterName  = null;
       this.branchId  =null;
       this.isEmptyContainer  = null;
       this.isCustomOfficer  = null;
       this.checkOutOperator  = null;
       this.customOfficer  = null;
       this.customOutDateTime  = null;
       this.customDateTime  = null;
       this.customOutDate  = null;
       this.isEdited  = null;
       this.isForParking  = null;
       this.receiptError  = null;
       this.searchText  = null;
       this.searchby  = null;
       this.id  = null;
       this.entryType  = null;
       this.roadType  = null;
       this.stateAbbrivation  = null;
       this.districtCode  = null;
       this.series  = null;
       this.seriesNumber  =null;
       this.containerSeries  = null;
       this.containerNumber  = null;
       this.containerSeries2  = null;
       this.containerNumber2  =null;
       this.isDeleted  = null;
       this.addedBy  =null;
       this.addedOn  = null;
       this.inDateTime  =null;
       this.updatedBy  = null;
       this.updatedOn  = null;
       this.receiptNo  = null;
       this.addedDate  = null;
       this.checkOutDateTime  =null ;
       this.outDateTime  = null;
       this.outDate  = null;
       this.transporter  = null;
       this.transporterId  =null;
       this.sealNumber1  = null;
       this.sealNumber2  = null;
       this.sealNumber3  =null ;
       this.sealNumber4  = null;
       this.chaNumber  = null;
       this.shippingBillNumber  =null ;
       this.shippingBillDate  = null;
       this.vessel  = null;
       this.pinNumber  = null;
       this.paymentMode  = null;
       this.containerType  =null ;
       this.driverName  =null ;
       this.driverContactNumber  =null;
       this.cutOffDate1  = null;
       this.cutOffDate2  = null;
       this.isCutOffValid  = null;
       this.isGTIContainerApproved  =null ;
       this.allowEditingEntry  = null;
      
    }
}
